version: "3"

services:
  ui:
    build: ../ui
    environment:
      - NODE_ENV={{NODE_ENV}}
    ports:
      - "{{EIGEN_SECRET_PORT}}:80"
    networks:
      - default
  proxy:
    build: ./proxy/
    ports:
      - "{{EIGEN_PROXY_PORT}}:8443"
    networks:
      - default
    external_links:
      - {{EIGEN_SERVICE_ADDR}}_1:eigen_service
  server:
    build: .
    ports:
      - "{{EIGEN_SERVICE_PORT}}:3000"
    networks:
      - default
    volumes:
      - "./data:/app/data"
    external_links:
      - eigen_service_3-tss-sm-server_1:tss-sm-server
networks:
  default:
    driver: bridge
