name: Eigen Lint Commit Messages
on:
  push:
    branches: 
      - main
      - zkpay_dev
  pull_request:
    branches:
      - main
      - zkpay_dev

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .commitlintrc.js
          firstParent: true