# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Eigen Secret UT
on:
  push:
    branches: 
      - main
      - zkpay_dev
  pull_request:
    branches:
      - main
      - zkpay_dev

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Download universal key
        run: curl https://universal-setup.ams3.digitaloceanspaces.com/setup_2^20.key -o ${{ github.workspace }}/circuits/setup_2^20.key
      - name: Download Circom
        run: git clone https://github.com/DanTehrani/circom-secq && cd circom-secq && cargo build --release && cargo install --path circom
      - name: Download ZKIT
        run: wget https://github.com/0xEigenLabs/eigen-zkvm/releases/download/v0.0.1/x86_64-unknown-linux-gnu.tar.gz && tar -xzvf x86_64-unknown-linux-gnu.tar.gz && chmod u+x zkit && mv zkit /usr/local/bin/
      - name: create server.env file
        run: touch .env && echo "NODE_ENV=test" >> .env && echo "PRIVATE_KEY=0000000000000000000000000000000000000000000000000000000000000000" >> .env && echo "DUNE_API_KEY=pI9TzC8FT6mbUShRoqg1k9MDlIulvi1p" >> .env && mv .env server
      - name: Compile contract
        run: npm run build
      - name: delete db
        run: rm -rf ./data
      - name: Start test
        run: npm run test
