# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Eigen ZKZRU CI
on:
  push:
    branches: [ main, zkpay_dev ]
  pull_request:
    branches: [ main, zkpay_dev ]
jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Compile contract
        run: npx hardhat compile
      - name: Download universal key
        run: curl https://universal-setup.ams3.digitaloceanspaces.com/setup_2^20.key -o ${{ github.workspace }}/circuits/setup_2^20.key
      - name: Download Circom
        run: wget https://github.com/iden3/circom/releases/download/v2.1.0/circom-linux-amd64 && chmod u+x circom-linux-amd64 && mv circom-linux-amd64 /usr/local/bin/circom
      - name: Download ZKIT
        run: wget wget https://github.com/0xEigenLabs/eigen-zkvm/archive/refs/tags/v0.0.1.tar.gz && tar -xzvf v0.0.1.tar.gz && cd eigen-zkvm-0.0.1 && cargo build --release && chmod u+x target/release/zkit && mv target/release/zkit /usr/local/bin/
      - name: Start hardhat node
        run: nohup npx hardhat node &
      - name: Generate circuits
        run: git submodule update --init #bash -x scripts/zkit_zktx.sh
      - name: Start test
        run: npm run test
