# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Eigen ZKZRU CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CIRCUIT_PATH: ${{ github.workspace }}/circuits/
  TEST_PATH: ${{ github.workspace }}/test/
  NODE_ENV: development

jobs:
  build-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: set ENV
        run: export CIRCUIT_PATH=env.CIRCUIT_PATH && export TEST_PATH=env.TEST_PATH && export NODE_ENV=env.NODE_ENV
      - uses: actions/checkout@v2
      - uses: taiki-e/github-actions/install-rust@main
        with:
          toolchain: nightly
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{runner.OS}}-npm-caches-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      - name: Compile contract
        run: npx hardhat compile
      - name: Build EigenZKit
        run: git clone https://github.com/ieigen/EigenZKit.git && cd EigenZKit && cargo build --release
        env: 
          ZKIT: ${{ github.workspace }}/EigenZKit/target/release/zkit
      - name: set ZKIT
        run: export ZKIT=env.ZKIT
      - name: Start hardhat node
        run: nohup npx hardhat node & 
      - name: Start test
        run: yarn test
